package main






























































































































































































































































































}	return nil	}		return app.Dao().DeleteRecord(record)		}			return err		if err != nil {		record, err := app.Dao().FindRecordById(collection.Id, change.EntityID)	case "delete":		return app.Dao().SaveRecord(record)		record.Set("sync_version", serverVersion+1)		record.Set("sync_status", "synced")		}			}				record.Set(key, value)			if key != "id" && key != "tenant_id" {		for key, value := range change.Data {		}			return nil // For now, skip conflicting updates			// Conflict detected - could create a conflict record here		if serverVersion > change.LocalVersion {		serverVersion := record.GetInt("sync_version")		// Check for conflicts		}			return err		if err != nil {		record, err := app.Dao().FindRecordById(collection.Id, change.EntityID)	case "update":		return app.Dao().SaveRecord(record)		record.Set("sync_version", change.LocalVersion+1)		record.Set("sync_status", "synced")		record.Set("tenant_id", tenantID)		}			record.Set(key, value)		for key, value := range change.Data {		record := models.NewRecord(collection)	case "create":	switch change.Operation {	}		return err	if err != nil {	collection, err := app.Dao().FindCollectionByNameOrId(change.EntityType)func processChange(app *pocketbase.PocketBase, tenantID string, change SyncChange) error {// processChange applies a single change to the database}	})		"serverTime":       time.Now().Format(time.RFC3339),		"pendingConflicts": pendingConflicts,		"tenantId":         tenantID,	return c.JSON(http.StatusOK, map[string]interface{}{	}		pendingConflicts = len(records)		)			map[string]interface{}{"tenantId": tenantID},			0,			0,			"",			"tenant_id = {:tenantId} && resolution = ''",			conflictsCollection.Id,		records, _ := app.Dao().FindRecordsByFilter(	if conflictsCollection != nil {	pendingConflicts := 0	conflictsCollection, _ := app.Dao().FindCollectionByNameOrId("sync_conflicts")	// Count pending conflicts	}		return apis.NewBadRequestError("Tenant ID is required", nil)	if tenantID == "" {	tenantID := getTenantID(c)func handleSyncStatus(c echo.Context, app *pocketbase.PocketBase) error {// handleSyncStatus returns current sync status for the tenant}	})		"status": "resolved",	return c.JSON(http.StatusOK, map[string]string{	}		return apis.NewBadRequestError("Failed to save resolution", err)	if err := app.Dao().SaveRecord(conflict); err != nil {	}		conflict.Set("merged_data", string(mergedJSON))		mergedJSON, _ := json.Marshal(req.MergedData)	if req.Resolution == "merged" && req.MergedData != nil {	conflict.Set("resolved_at", time.Now().Format(time.RFC3339))	conflict.Set("resolution", req.Resolution)	// Apply resolution	}		return apis.NewNotFoundError("Conflict not found", err)	if err != nil {	conflict, err := app.Dao().FindRecordById(collection.Id, req.ConflictID)	}		return apis.NewNotFoundError("Sync conflicts collection not found", err)	if err != nil {	collection, err := app.Dao().FindCollectionByNameOrId("sync_conflicts")	// Find the conflict record	}		return apis.NewBadRequestError("Invalid request body", err)	if err := c.Bind(&req); err != nil {	}		MergedData map[string]interface{} `json:"mergedData,omitempty"`		Resolution string `json:"resolution"` // local_wins, remote_wins, merged		ConflictID string `json:"conflictId"`	var req struct {func handleSyncResolve(c echo.Context, app *pocketbase.PocketBase) error {// handleSyncResolve processes conflict resolution}	return c.JSON(http.StatusOK, response)	}		HasMore:         false, // Implement pagination if needed		ServerTimestamp: time.Now().Format(time.RFC3339),		Changes:         changes,	response := SyncPullResponse{	}		}			})				LocalVersion: record.GetInt("sync_version"),				Data:         data,				Operation:    "update",				EntityID:     record.Id,				EntityType:   collName,			changes = append(changes, SyncChange{			}				data[key] = value			for key, value := range record.PublicExport() {			data := map[string]interface{}{}		for _, record := range records {		}			continue		if err != nil {		)			},				"since":    since,				"tenantId": tenantID,			map[string]interface{}{			0,			100,			"-updated",			"tenant_id = {:tenantId} && updated >= {:since}",			coll.Id,		records, err := app.Dao().FindRecordsByFilter(		}			continue		if err != nil {		coll, err := app.Dao().FindCollectionByNameOrId(collName)	for _, collName := range collections {	collections := []string{"products", "categories", "customers", "sales", "inventory_movements"}	changes := []SyncChange{}	// Get changes from various collections	}		since = time.Now().Add(-24 * time.Hour).Format(time.RFC3339)		// Default to 24 hours ago	if since == "" {	since := c.QueryParam("since")	}		return apis.NewBadRequestError("Tenant ID is required", nil)	if tenantID == "" {	tenantID := getTenantID(c)func handleSyncPull(c echo.Context, app *pocketbase.PocketBase) error {// handleSyncPull retrieves changes since a given timestamp}	return c.JSON(http.StatusOK, result)	}		}			result.Synced++		} else {			result.Success = false			result.Errors = append(result.Errors, err.Error())		if err != nil {		err := processChange(app, req.TenantID, change)	for _, change := range req.Changes {	}		Synced:  0,		Success: true,	result := SyncResult{	}		return apis.NewForbiddenError(err.Error(), nil)	if err := validateTenantAccess(c, req.TenantID); err != nil {	// Validate tenant access	}		return apis.NewBadRequestError("Invalid request body", err)	if err := c.Bind(&req); err != nil {	var req SyncPushRequestfunc handleSyncPush(c echo.Context, app *pocketbase.PocketBase) error {// handleSyncPush processes incoming changes from client}	}, apis.RequireRecordAuth())		return handleSyncStatus(c, app)	e.Router.GET("/api/sync/status", func(c echo.Context) error {	// Get sync status	}, apis.RequireRecordAuth())		return handleSyncResolve(c, app)	e.Router.POST("/api/sync/resolve", func(c echo.Context) error {	// Resolve a conflict	}, apis.RequireRecordAuth())		return handleSyncPull(c, app)	e.Router.GET("/api/sync/pull", func(c echo.Context) error {	// Pull remote changes from server	}, apis.RequireRecordAuth())		return handleSyncPush(c, app)	e.Router.POST("/api/sync/push", func(c echo.Context) error {	// Push local changes to serverfunc setupSyncRoutes(e *core.ServeEvent, app *pocketbase.PocketBase) {// setupSyncRoutes configures the sync API endpoints}	Errors    []string       `json:"errors,omitempty"`	Conflicts []SyncConflict `json:"conflicts,omitempty"`	Synced    int            `json:"synced"`	Success   bool           `json:"success"`type SyncResult struct {// SyncResult represents the result of a sync operation}	RemoteData map[string]interface{} `json:"remoteData"`	LocalData  map[string]interface{} `json:"localData"`	EntityID   string                 `json:"entityId"`	EntityType string                 `json:"entityType"`type SyncConflict struct {// SyncConflict represents a sync conflict}	HasMore         bool         `json:"hasMore"`	ServerTimestamp string       `json:"serverTimestamp"`	Changes         []SyncChange `json:"changes"`type SyncPullResponse struct {// SyncPullResponse represents a sync pull response}	LocalVersion int                    `json:"localVersion"`	Data         map[string]interface{} `json:"data"`	Operation    string                 `json:"operation"` // create, update, delete	EntityID     string                 `json:"entityId"`	EntityType   string                 `json:"entityType"`type SyncChange struct {// SyncChange represents a single change to sync}	ClientTimestamp string       `json:"clientTimestamp"`	Changes         []SyncChange `json:"changes"`	TenantID        string       `json:"tenantId"`type SyncPushRequest struct {// SyncPushRequest represents a sync push request)	"github.com/pocketbase/pocketbase/core"	"github.com/pocketbase/pocketbase/apis"	"github.com/pocketbase/pocketbase"	"github.com/labstack/echo/v5"	"time"	"net/http"	"encoding/json"import (package main