const GENERATED_PASSPHRASE_BYTES = 24;

interface BackupSecureRandom {
  getRandomValues: (target: Uint8Array<ArrayBuffer>) => void;
}

const browserSecureRandom: BackupSecureRandom | null =
  typeof globalThis.crypto?.getRandomValues === 'function'
    ? {
        getRandomValues: target => {
          globalThis.crypto.getRandomValues(target);
        },
      }
    : null;

/**
 * Generate a 192-bit recovery passphrase using the browser's CSPRNG.
 * Grouping is presentation-only; every generated byte remains encoded in the
 * base64url payload and the main process applies the existing NFKC contract.
 */
export function generateBackupPassphrase(
  secureRandom: BackupSecureRandom | null = browserSecureRandom
): string {
  if (!secureRandom || typeof secureRandom.getRandomValues !== 'function') {
    throw new Error('SECURE_RANDOM_UNAVAILABLE');
  }
  const bytes = new Uint8Array(new ArrayBuffer(GENERATED_PASSPHRASE_BYTES));
  secureRandom.getRandomValues(bytes);
  let binary = '';
  for (const byte of bytes) binary += String.fromCharCode(byte);
  const encoded = btoa(binary).replaceAll('+', '-').replaceAll('/', '_').replace(/=+$/, '');
  return encoded.match(/.{1,8}/g)!.join('.');
}
