/**
 * Device registry service.
 *
 * Tracks every cashier machine that mutates the local store. The
 * Electron desktop binary or the web client registers itself once via
 * `auth.registerDevice` and persists the server-issued id locally.
 * The Command Envelope middleware validates `(tenantId, deviceId)`
 * ownership on every critical mutation per ADR-0002.
 *
 * All public functions are tenant-scoped — there is no global lookup
 * surface. A device id from tenant A cannot be used on tenant B.
 *
 * @module services/devices/devicesService
 */

import { and, eq } from 'drizzle-orm';
import { nanoid } from 'nanoid';
import type { DatabaseInstance } from '../../db/index.js';
import { devices, users, type DeviceAuthorityRole, type DeviceKind } from '../../db/schema.js';
import { createModuleLogger } from '../../logging/logger.js';
import { inferAuthorityRole } from './authority.js';
import { throwServerError } from '../../lib/errorCodes.js';

const log = createModuleLogger('devices');

// explicit `| undefined` on Zod-optional fields.
export interface RegisterDeviceInput {
  tenantId: string;
  userId: string;
  kind: DeviceKind;
  name: string;
  /** Optional client hint — server still re-checks uniqueness. */
  deviceId?: string | undefined;
  /** Free-form JSON metadata (OS, browser UA, install path, etc.). */
  metadata?: Record<string, unknown> | undefined;
  authorityRole?: DeviceAuthorityRole | undefined;
  pairedSiteId?: string | null | undefined;
  appVersion?: string | null | undefined;
  dbSchemaVersion?: number | null | undefined;
  /**
   * Internal-only authorization for a deliberate identity handoff. Ordinary
   * auth.registerDevice calls must leave this false so a still-valid token
   * from a prior cashier cannot steal the terminal back after switchStaff.
   */
  allowIdentityChange?: boolean | undefined;
  /**
   * Runs inside the same writer transaction before this device changes user.
   * Auth uses it to park the prior cashier's active claims atomically.
   */
  onIdentityChange?:
    | ((
        tx: DatabaseInstance,
        change: { deviceId: string; previousUserId: string; nextUserId: string; now: string }
      ) => void)
    | undefined;
}

export interface RegisteredDevice {
  deviceId: string;
  registeredAt: string;
}

/**
 * Idempotent device registration for the SAME active actor. If
 * `input.deviceId` names a terminal currently bound to another actor, the
 * ordinary auth path fails closed; only an internal caller with both
 * `allowIdentityChange` and an atomic parking callback may perform a handoff.
 * Otherwise a missing/inactive id creates a new server-minted row.
 *
 * Cross-tenant collisions on `deviceId` are impossible because the
 * id is server-generated by default and the unique constraint on the
 * primary key + the tenant scope query prevent reuse.
 */
export async function registerDevice(
  db: DatabaseInstance,
  input: RegisterDeviceInput,
  now: Date = new Date()
): Promise<RegisteredDevice> {
  const nowIso = now.toISOString();
  const authorityRole = input.authorityRole ?? inferAuthorityRole(input.kind);
  const result = db.transaction(
    tx => {
      if (input.deviceId) {
        const existing = tx
          .select({
            id: devices.id,
            isActive: devices.isActive,
            activeUserId: devices.activeUserId,
            identityVersion: devices.identityVersion,
          })
          .from(devices)
          .where(and(eq(devices.tenantId, input.tenantId), eq(devices.id, input.deviceId)))
          .get();

        if (existing && existing.isActive) {
          const identityChanged = existing.activeUserId !== input.userId;
          if (identityChanged && existing.activeUserId) {
            if (!input.allowIdentityChange) {
              throwServerError({
                trpcCode: 'UNAUTHORIZED',
                errorCode: 'AUTH_IDENTITY_CHANGED',
                message: 'The active user for this device changed before registration completed',
              });
            }
            if (!input.onIdentityChange) {
              throw new Error(
                'Rebinding an active device identity requires an atomic identity-change handler'
              );
            }
            input.onIdentityChange(tx as unknown as DatabaseInstance, {
              deviceId: existing.id,
              previousUserId: existing.activeUserId,
              nextUserId: input.userId,
              now: nowIso,
            });
          }
          // Idempotent metadata refresh. The identity generation advances only
          // when a different authenticated user takes over this device.
          const updateData: Partial<typeof devices.$inferInsert> = {
            kind: input.kind,
            name: input.name,
            authorityRole,
            appVersion: input.appVersion ?? null,
            dbSchemaVersion: input.dbSchemaVersion ?? null,
            metadata: input.metadata ?? null,
            activeUserId: input.userId,
            ...(identityChanged ? { identityVersion: existing.identityVersion + 1 } : {}),
            lastSeenAt: nowIso,
            updatedAt: nowIso,
          };
          if (input.pairedSiteId !== undefined) {
            updateData.pairedSiteId = input.pairedSiteId;
          }
          tx.update(devices)
            .set(updateData)
            .where(and(eq(devices.tenantId, input.tenantId), eq(devices.id, input.deviceId)))
            .run();
          return { deviceId: existing.id, registeredAt: nowIso, created: false };
        }
      }

      const newId = nanoid();
      tx.insert(devices)
        .values({
          id: newId,
          tenantId: input.tenantId,
          kind: input.kind,
          name: input.name,
          registeredByUserId: input.userId,
          activeUserId: input.userId,
          identityVersion: 1,
          lastSeenAt: nowIso,
          authorityRole,
          pairedSiteId: input.pairedSiteId ?? null,
          appVersion: input.appVersion ?? null,
          dbSchemaVersion: input.dbSchemaVersion ?? null,
          isActive: true,
          metadata: input.metadata ?? null,
          createdAt: nowIso,
          updatedAt: nowIso,
        })
        .run();
      return { deviceId: newId, registeredAt: nowIso, created: true };
    },
    { behavior: 'immediate' }
  );

  if (result.created) {
    log.info(
      {
        tenantId: input.tenantId,
        deviceId: result.deviceId,
        kind: input.kind,
        userId: input.userId,
      },
      'device registered'
    );
  }

  return { deviceId: result.deviceId, registeredAt: result.registeredAt };
}

export interface ActiveDevice {
  id: string;
  tenantId: string;
  kind: DeviceKind;
  name: string;
  activeUserId: string | null;
  identityVersion: number;
}

/**
 * Find an active device row for the (tenantId, deviceId) pair.
 * Returns `null` when the device does not exist, belongs to a
 * different tenant, or has been deactivated. The caller should map
 * `null` to `DEVICE_NOT_REGISTERED`.
 */
export async function findActiveDevice(
  db: DatabaseInstance,
  args: { tenantId: string; deviceId: string }
): Promise<ActiveDevice | null> {
  const row = await db
    .select({
      id: devices.id,
      tenantId: devices.tenantId,
      kind: devices.kind,
      name: devices.name,
      activeUserId: devices.activeUserId,
      identityVersion: devices.identityVersion,
      isActive: devices.isActive,
    })
    .from(devices)
    .where(and(eq(devices.tenantId, args.tenantId), eq(devices.id, args.deviceId)))
    .get();

  if (!row || !row.isActive) return null;
  return {
    id: row.id,
    tenantId: row.tenantId,
    kind: row.kind,
    name: row.name,
    activeUserId: row.activeUserId,
    identityVersion: row.identityVersion,
  };
}

export type ClaimedDeviceIdentity =
  | { state: 'active'; device: ActiveDevice }
  | { state: 'missing' }
  | { state: 'different_user'; activeUserId: string };

/**
 * Claim a legacy/unbound device for the authenticated user or validate its
 * existing binding. The immediate transaction makes first-use adoption
 * deterministic when two stale sessions race after an upgrade.
 */
export async function claimActiveDeviceIdentity(
  db: DatabaseInstance,
  args: {
    tenantId: string;
    deviceId: string;
    userId: string;
    /** JWT identity required for production adoption; direct fixtures may omit it. */
    expectedIdentity?: { sessionVersion: number; role: string };
  }
): Promise<ClaimedDeviceIdentity> {
  const initial = await db
    .select({
      id: devices.id,
      tenantId: devices.tenantId,
      kind: devices.kind,
      name: devices.name,
      activeUserId: devices.activeUserId,
      identityVersion: devices.identityVersion,
      isActive: devices.isActive,
    })
    .from(devices)
    .where(and(eq(devices.tenantId, args.tenantId), eq(devices.id, args.deviceId)))
    .get();
  if (!initial || !initial.isActive) return { state: 'missing' };
  if (initial.activeUserId && initial.activeUserId !== args.userId) {
    return { state: 'different_user', activeUserId: initial.activeUserId };
  }
  if (initial.activeUserId === args.userId) {
    return {
      state: 'active',
      device: {
        id: initial.id,
        tenantId: initial.tenantId,
        kind: initial.kind,
        name: initial.name,
        activeUserId: initial.activeUserId,
        identityVersion: initial.identityVersion,
      },
    };
  }

  // Only legacy rows with no active user need a writer. Ordinary commands pay
  // one indexed read and rely on final generation revalidation for races.
  return db.transaction(
    tx => {
      const row = tx
        .select({
          id: devices.id,
          tenantId: devices.tenantId,
          kind: devices.kind,
          name: devices.name,
          activeUserId: devices.activeUserId,
          identityVersion: devices.identityVersion,
          isActive: devices.isActive,
        })
        .from(devices)
        .where(and(eq(devices.tenantId, args.tenantId), eq(devices.id, args.deviceId)))
        .get();
      if (!row || !row.isActive) return { state: 'missing' } as const;
      if (row.activeUserId && row.activeUserId !== args.userId) {
        return { state: 'different_user', activeUserId: row.activeUserId } as const;
      }
      if (!row.activeUserId) {
        if (args.expectedIdentity) {
          const actor = tx
            .select({
              isActive: users.isActive,
              sessionVersion: users.sessionVersion,
              role: users.role,
            })
            .from(users)
            .where(and(eq(users.id, args.userId), eq(users.tenantId, args.tenantId)))
            .get();
          // Logout may have cleared the terminal after JWT verification. Do
          // not let that stale request commit a new binding to the old actor.
          if (
            !actor?.isActive ||
            actor.sessionVersion !== args.expectedIdentity.sessionVersion ||
            actor.role !== args.expectedIdentity.role
          ) {
            throwServerError({
              trpcCode: 'UNAUTHORIZED',
              errorCode: 'AUTH_IDENTITY_CHANGED',
              message: 'The authenticated identity changed before device adoption',
            });
          }
        }
        const changed = tx
          .update(devices)
          .set({
            activeUserId: args.userId,
            identityVersion: row.identityVersion + 1,
            updatedAt: new Date().toISOString(),
          })
          .where(
            and(
              eq(devices.id, args.deviceId),
              eq(devices.tenantId, args.tenantId),
              eq(devices.identityVersion, row.identityVersion)
            )
          )
          .run();
        if (changed.changes !== 1) return { state: 'missing' } as const;
        return {
          state: 'active',
          device: {
            id: row.id,
            tenantId: row.tenantId,
            kind: row.kind,
            name: row.name,
            activeUserId: args.userId,
            identityVersion: row.identityVersion + 1,
          },
        } as const;
      }
      return {
        state: 'active',
        device: {
          id: row.id,
          tenantId: row.tenantId,
          kind: row.kind,
          name: row.name,
          activeUserId: row.activeUserId,
          identityVersion: row.identityVersion,
        },
      } as const;
    },
    { behavior: 'immediate' }
  );
}

/**
 * Bump `last_seen_at` to track liveness. Cheap (one row update); the
 * Command Envelope middleware calls it on every successful critical
 * mutation so the Operations Center () can render device
 * health later.
 */
export async function markSeen(
  db: DatabaseInstance,
  args: { tenantId: string; deviceId: string },
  now: Date = new Date()
): Promise<void> {
  const nowIso = now.toISOString();
  await db
    .update(devices)
    .set({ lastSeenAt: nowIso, updatedAt: nowIso })
    .where(and(eq(devices.tenantId, args.tenantId), eq(devices.id, args.deviceId)));
}

/**
 * Soft-delete: marks the device inactive without removing the row,
 * so audit history (operation journal in ) can still join
 * via `audit_logs.operation_id` later.
 */
export async function deactivateDevice(
  db: DatabaseInstance,
  args: { tenantId: string; deviceId: string },
  now: Date = new Date()
): Promise<void> {
  const nowIso = now.toISOString();
  await db
    .update(devices)
    .set({ isActive: false, updatedAt: nowIso })
    .where(and(eq(devices.tenantId, args.tenantId), eq(devices.id, args.deviceId)));
}
