/**
 * ENG-052 — Device registry service.
 *
 * Tracks every cashier machine that mutates the local store. The
 * Electron desktop binary or the web client registers itself once via
 * `auth.registerDevice` and persists the server-issued id locally.
 * The Command Envelope middleware validates `(tenantId, deviceId)`
 * ownership on every critical mutation per ADR-0002.
 *
 * All public functions are tenant-scoped — there is no global lookup
 * surface. A device id from tenant A cannot be used on tenant B.
 *
 * @module services/devices/devicesService
 */

import { and, eq } from 'drizzle-orm';
import { nanoid } from 'nanoid';
import type { DatabaseInstance } from '../../db/index.js';
import {
  devices,
  type DeviceAuthorityRole,
  type DeviceKind,
} from '../../db/schema.js';
import { createModuleLogger } from '../../logging/logger.js';
import { inferAuthorityRole } from './authority.js';

const log = createModuleLogger('devices');

// ENG-179b — explicit `| undefined` on Zod-optional fields.
export interface RegisterDeviceInput {
  tenantId: string;
  userId: string;
  kind: DeviceKind;
  name: string;
  /** Optional client hint — server still re-checks uniqueness. */
  deviceId?: string | undefined;
  /** Free-form JSON metadata (OS, browser UA, install path, etc.). */
  metadata?: Record<string, unknown> | undefined;
  authorityRole?: DeviceAuthorityRole | undefined;
  pairedSiteId?: string | null | undefined;
  appVersion?: string | null | undefined;
  dbSchemaVersion?: number | null | undefined;
}

export interface RegisteredDevice {
  deviceId: string;
  registeredAt: string;
}

/**
 * Idempotent device registration. If `input.deviceId` is supplied AND
 * an active row exists for the same tenant + id, returns it
 * unchanged. Otherwise creates a new row with a server-minted id.
 *
 * Cross-tenant collisions on `deviceId` are impossible because the
 * id is server-generated by default and the unique constraint on the
 * primary key + the tenant scope query prevent reuse.
 */
export async function registerDevice(
  db: DatabaseInstance,
  input: RegisterDeviceInput,
  now: Date = new Date()
): Promise<RegisteredDevice> {
  const nowIso = now.toISOString();
  const authorityRole = input.authorityRole ?? inferAuthorityRole(input.kind);

  if (input.deviceId) {
    const existing = await db
      .select({ id: devices.id, isActive: devices.isActive })
      .from(devices)
      .where(and(eq(devices.tenantId, input.tenantId), eq(devices.id, input.deviceId)))
      .get();

    if (existing && existing.isActive) {
      // Idempotent: same caller, same id, active → just bump last_seen.
      const updateData: Partial<typeof devices.$inferInsert> = {
        kind: input.kind,
        name: input.name,
        authorityRole,
        appVersion: input.appVersion ?? null,
        dbSchemaVersion: input.dbSchemaVersion ?? null,
        metadata: input.metadata ?? null,
        lastSeenAt: nowIso,
        updatedAt: nowIso,
      };
      if (input.pairedSiteId !== undefined) {
        updateData.pairedSiteId = input.pairedSiteId;
      }
      await db
        .update(devices)
        .set(updateData)
        .where(and(eq(devices.tenantId, input.tenantId), eq(devices.id, input.deviceId)));
      return { deviceId: existing.id, registeredAt: nowIso };
    }
  }

  const newId = nanoid();
  await db.insert(devices).values({
    id: newId,
    tenantId: input.tenantId,
    kind: input.kind,
    name: input.name,
    registeredByUserId: input.userId,
    lastSeenAt: nowIso,
    authorityRole,
    pairedSiteId: input.pairedSiteId ?? null,
    appVersion: input.appVersion ?? null,
    dbSchemaVersion: input.dbSchemaVersion ?? null,
    isActive: true,
    metadata: input.metadata ?? null,
    createdAt: nowIso,
    updatedAt: nowIso,
  });

  log.info(
    { tenantId: input.tenantId, deviceId: newId, kind: input.kind, userId: input.userId },
    'device registered'
  );

  return { deviceId: newId, registeredAt: nowIso };
}

export interface ActiveDevice {
  id: string;
  tenantId: string;
  kind: DeviceKind;
  name: string;
}

/**
 * Find an active device row for the (tenantId, deviceId) pair.
 * Returns `null` when the device does not exist, belongs to a
 * different tenant, or has been deactivated. The caller should map
 * `null` to `DEVICE_NOT_REGISTERED`.
 */
export async function findActiveDevice(
  db: DatabaseInstance,
  args: { tenantId: string; deviceId: string }
): Promise<ActiveDevice | null> {
  const row = await db
    .select({
      id: devices.id,
      tenantId: devices.tenantId,
      kind: devices.kind,
      name: devices.name,
      isActive: devices.isActive,
    })
    .from(devices)
    .where(and(eq(devices.tenantId, args.tenantId), eq(devices.id, args.deviceId)))
    .get();

  if (!row || !row.isActive) return null;
  return {
    id: row.id,
    tenantId: row.tenantId,
    kind: row.kind,
    name: row.name,
  };
}

/**
 * Bump `last_seen_at` to track liveness. Cheap (one row update); the
 * Command Envelope middleware calls it on every successful critical
 * mutation so the Operations Center (ENG-065) can render device
 * health later.
 */
export async function markSeen(
  db: DatabaseInstance,
  args: { tenantId: string; deviceId: string },
  now: Date = new Date()
): Promise<void> {
  const nowIso = now.toISOString();
  await db
    .update(devices)
    .set({ lastSeenAt: nowIso, updatedAt: nowIso })
    .where(and(eq(devices.tenantId, args.tenantId), eq(devices.id, args.deviceId)));
}

/**
 * Soft-delete: marks the device inactive without removing the row,
 * so audit history (operation journal in ENG-053) can still join
 * via `audit_logs.operation_id` later.
 */
export async function deactivateDevice(
  db: DatabaseInstance,
  args: { tenantId: string; deviceId: string },
  now: Date = new Date()
): Promise<void> {
  const nowIso = now.toISOString();
  await db
    .update(devices)
    .set({ isActive: false, updatedAt: nowIso })
    .where(and(eq(devices.tenantId, args.tenantId), eq(devices.id, args.deviceId)));
}
