-- ENG-039d2 — sale_items.notes: per-line modifier text.
--
-- The voice-ordering surface (ENG-039a) already captures per-item
-- modifiers ("sin cebolla", "extra queso") in a Map<itemKey,string>
-- on the React component side. Pre-ENG-039d2 those notes were
-- aggregated into the sale-level `sales.notes` field as free text
-- because no per-row destination existed. This migration adds the
-- per-row column so the voice surface can persist notes inline with
-- each `sale_items` row and the KDS snapshot can render them
-- alongside the product name instead of pooled at the bottom of the
-- ticket.
--
-- ALTER TABLE on better-sqlite3 only fails if the column already
-- exists. The ENG-002 adoption shim re-runs migrations idempotently
-- on databases that already carry the target shape; a CREATE TABLE
-- IF NOT EXISTS guard does not apply here because we are adding a
-- column to an existing table. The shim handles the duplicate-column
-- error gracefully — see packages/server/src/db/index.ts adoption
-- logic — so a re-run of this migration on a DB that already has
-- the column is a no-op.

ALTER TABLE `sale_items` ADD COLUMN `notes` text;
