// Dynamic lucide icon resolver for the secondary pages.
//
// The design prototypes used a Babel-in-browser `<Icon name="scan-line" />`
// helper backed by the lucide UMD build (kebab-case names). Here we keep that
// kebab-case `name` API but resolve it through an explicit named-import map so
// Vite tree-shakes lucide-react down to only the icons the pages use — a
// `import * as Lucide` barrel would otherwise pull all ~5000 icons into the
// shared chunk. Add a new entry to ICONS when a page references a new name.
import {
  Apple,
  ArrowDownToLine,
  ArrowLeftRight,
  ArrowRight,
  ArrowUp,
  ArrowUpRight,
  BarChart2,
  Bell,
  BookOpen,
  Calendar,
  Check,
  CheckCircle2,
  ChevronDown,
  ChevronRight,
  Clock,
  Code2,
  Coffee,
  Download,
  Edit3,
  Feather,
  FileText,
  GitBranch,
  Github,
  Globe,
  Handshake,
  HeartHandshake,
  History,
  Image,
  Info,
  Languages,
  LifeBuoy,
  Lightbulb,
  Lock,
  Mail,
  Map,
  MapPin,
  MessageCircle,
  Newspaper,
  OctagonAlert,
  Package,
  Play,
  Printer,
  RefreshCw,
  Rocket,
  ScanLine,
  Search,
  SearchX,
  Send,
  ShieldCheck,
  ShoppingBag,
  ShoppingCart,
  Sparkles,
  Square,
  ThumbsDown,
  ThumbsUp,
  TriangleAlert,
  User,
  Wallet,
  Warehouse,
  Wifi as WifiIcon,
  WifiOff,
  Wrench,
  X,
  Circle,
} from 'lucide-react';

const ICONS = {
  apple: Apple,
  'alert-octagon': OctagonAlert,
  'alert-triangle': TriangleAlert,
  'arrow-down-to-line': ArrowDownToLine,
  'arrow-left-right': ArrowLeftRight,
  'arrow-right': ArrowRight,
  'arrow-up': ArrowUp,
  'arrow-up-right': ArrowUpRight,
  'bar-chart-2': BarChart2,
  bell: Bell,
  'book-open': BookOpen,
  calendar: Calendar,
  check: Check,
  'check-circle-2': CheckCircle2,
  'chevron-down': ChevronDown,
  'chevron-right': ChevronRight,
  clock: Clock,
  'code-2': Code2,
  coffee: Coffee,
  // The design uses a tiny "dot" bullet; lucide's Circle stands in for it.
  dot: Circle,
  download: Download,
  'edit-3': Edit3,
  feather: Feather,
  'file-text': FileText,
  'git-branch': GitBranch,
  github: Github,
  globe: Globe,
  handshake: Handshake,
  'heart-handshake': HeartHandshake,
  history: History,
  image: Image,
  info: Info,
  languages: Languages,
  'life-buoy': LifeBuoy,
  lightbulb: Lightbulb,
  lock: Lock,
  mail: Mail,
  map: Map,
  'map-pin': MapPin,
  'message-circle': MessageCircle,
  newspaper: Newspaper,
  package: Package,
  play: Play,
  printer: Printer,
  'refresh-cw': RefreshCw,
  rocket: Rocket,
  'scan-line': ScanLine,
  search: Search,
  'search-x': SearchX,
  send: Send,
  'shield-check': ShieldCheck,
  'shopping-bag': ShoppingBag,
  'shopping-cart': ShoppingCart,
  sparkles: Sparkles,
  square: Square,
  'thumbs-down': ThumbsDown,
  'thumbs-up': ThumbsUp,
  user: User,
  wallet: Wallet,
  warehouse: Warehouse,
  wifi: WifiIcon,
  'wifi-off': WifiOff,
  wrench: Wrench,
  x: X,
};

export function Icon({ name, size = 18, color, className = '', style = {} }) {
  const Cmp = ICONS[name] || Circle;
  return (
    <span
      className={className}
      style={{
        display: 'inline-flex',
        alignItems: 'center',
        justifyContent: 'center',
        width: size,
        height: size,
        color: color || 'currentColor',
        ...style,
      }}
    >
      <Cmp size={size} strokeWidth={1.5} />
    </span>
  );
}
